### ISSUE TITLE
The property 'Name' cannot be found on this object.

### ISSUE THREAD

**Issue by troyinsight** [SQLPlayer/azure.datafactory.devops#106]
Hello,

Trying to run PublishADFTask@1, I'm getting right down to the end before receiving what seems to be a PowerShell error.

```
STEP: Replacing all properties environment-related...
Config file:   D:\a\1\s\deployment\config-***.csv
Validation of config file completed.
##[error]The property 'Name' cannot be found on this object. Verify that the property exists.
Finishing: Push code to Data Factory
```

I'm just running a single task, updating some values via a CSV.

```
  - task: PublishADFTask@1
    displayName: 'Push code to Data Factory'
    inputs:
      ConnectedServiceName: ${{ parameters.serviceConnectionName }}
      ResourceGroupName: $(CustomerResourceGroupName)
      DataFactoryName: $(CustomerDataFactoryName)
      Location: $(CustomerLocation)
      DataFactoryCodePath: '$(Agent.BuildDirectory)\s'
      StopStartTriggers: false
      CreateNewInstance: false
      IgnoreLackOfReferencedObject: false
      StageType: Stage
      StageCode: $(Environment)
      FilteringType: 'Inline'
      FilterText: |
        -trigger.*
        -factory.*
      PublishMethod: 'AzResource'
```

Do you have any ideas?
