### ISSUE TITLE
The job is still successful after the task fails

### ISSUE THREAD

**Issue by uedring** [SQLPlayer/azure.datafactory.devops#36]
I have a Build Pipeline with only one job and continueOnError is set to false, but after the Build ADF Task fails, the job status is still successful. How can this be resolved?

Here is the yml:
```
trigger: none

continueOnError: false

pool:
  vmImage: 'windows-latest'

variables:
  factoryName: 'TargetingDataFactory'

steps:
    - task: BuildADFTask@1
      inputs:
        DataFactoryCodePath: '$(factoryName)'
        Action: 'Build'
```

![image](https://user-images.githubusercontent.com/54339807/111428141-11b32600-8732-11eb-9e32-c28314536160.png)
