### ISSUE TITLE
Invalid 'dependsOn' attribute should fail BuildADFTask

### ISSUE THREAD

**Issue by PHPirates** [SQLPlayer/azure.datafactory.devops#69]
We are using the BuildADFTask to validate the ADF files in our CI pipeline, but if there is a pipeline in which an activity has a dependsOn attribute on an activity that does not actually exist, the validate step succeeds even though when run the pipeline will fail.
Is this a bug in the Data Factory itself, or can it be fixed in this task?

Example pipeline:

```json
{
    "name": "pipeline1",
    "properties": {
        "activities": [
            {
                "name": "Wait1",
                "type": "Wait",
                "dependsOn": [],
                "userProperties": [],
                "typeProperties": {
                    "waitTimeInSeconds": 1
                }
            },
            {
                "name": "Wait2",
                "type": "Wait",
                "dependsOn": [
			{
				"activity": "does-not-exist",
				"dependencyConditions": [
					"Succeeded"
				]
			}
		],
                "userProperties": [],
                "typeProperties": {
                    "waitTimeInSeconds": 1
                }
            }
        ],
        "annotations": []
    }
}
```

It validates, but produces this error when run:
```
ErrorCode=InvalidTemplate, ErrorMessage=The template validation failed: 'The 'runAfter' property of template action 'bad_lossScope' contains non-existent action: 'employmentScope'
```

Our yml:
```
- job: 'adf'
  displayName: 'Data Factory'
  pool:
    vmImage: 'windows-latest'
  steps:
    - task: SQLPlayer.DataFactoryTools.BuildADF.BuildADFTask@1
      displayName: 'Validate ADF files'
      inputs:
        DataFactoryCodePath: '$(System.DefaultWorkingDirectory)/data-factory'
```

It isn't clear to me whether this task is using the same functionality as the 'validate all' button in the UI, I'm confused by the readme: it has a 'Build only' section, and then a 'Validate & Export ARM Template' section which mentions the azure-data-factory-utilities npm package, but also a 'Build only' action of which I don't know whether it is the same as the 'Build only' of the previous section. I looked in the source and it does seem like some checks are implemented in this repo.
