### ISSUE TITLE
Unknown object type: Credential

### ISSUE THREAD

**Issue by peterbud** [SQLPlayer/azure.datafactory.devops#76]
I have an ADF source which contains a credential:
![image](https://user-images.githubusercontent.com/7863452/145439151-d70ffebf-fbae-4065-aa81-a241ff685e78.png)

Having a step like this:
```
steps:
- task: BuildADFTask@1
  displayName: 'Build and test ADF'
  inputs:
    DataFactoryCodePath: 'src/adf'
    Action: 'Build'

```

Leads to this error:
`##[error]ADFT0029: Unknown object type: Credential.`

Is that expected, or is this an error?
